version: 2.1
jobs:
  job1:
    docker:
      - image: alpine:3.15

    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'


      - run:
          name : Second step
          command :
            echo 'Hi how are you ?'
            echo 'this is the second step'

workflows:
  sample-workflow:
    jobs:
      - job1